### ISSUE TITLE
Issues prepending fields with special characters.

### ISSUE THREAD

**Issue by suipaste** [struts-community-plugins/struts2-bootstrap#11]
I'm trying to prepend a text field with a pound sign £ but when the page is loaded the field is prepended with a � icon here is the code I am using:

`<s:textfield key="advance" maxlength="14" requiredLabel="true" inputPrepend="£" />`

I have tried various ways of escaping the character such as `&#163;` or `&pound;` but this prints the characters literally, I also tried or `&amp;#163;` on the off change there was some strange java escaping going on but that yielded the literally characters as well. Based on the examples in the bootstrap showcase I would think that just typing £ would work so I'm a little stumped as to what is not working.

Thanks

(edit - changed my escape sequences to code blocks so they don't escape!)

-I have since realised that there is a glyphicon which fills my use case but I still think this is a bug of some description.

**Comment by sdutry** [comment]
@suipaste 
I think this issue is not related to the usage of `struts2-bootstrap` at all.

It looks to be an encoding problem.

i've tried recreating the problem in the following github repository: 
* https://github.com/sdutry/struts2-bootstrap-issue11

Can you please check if this renders correctly for you (and let us know either way)?
Steps:

1. clone the repository localy
2. execute `mvn jetty:run`
3. check on http://localhost:8080/prepend

The only way i could recreate the problem was by setting my file in a non-UTF-8 encoding and specifying that it was UTF-8

The correct hex value in UTF-8 of the character is: `C2A3`
I checked this with 
* https://hexed.it/
* http://www.fileformat.info/info/unicode/char/00A3/index.htm
