### ISSUE TITLE
form-close.ftl should only include tooltop js if needed

### ISSUE THREAD

**Issue by perfnorm** [struts-community-plugins/struts2-bootstrap#7]
Surround with parameters.hasTooltip check.  (Can make the default true if need to support a version of struts2 that doesn't have hasTooltip defined yet)

```
<#if (parameters.hasTooltip)!false>
<script type="text/javascript">
    if (typeof jQuery != 'undefined') {
        if (typeof jQuery.fn.tooltip == 'function') {
            jQuery('i.s2b_tooltip').tooltip();
        }
    }
</script>
</#if>
```

**Comment by sdutry** [comment]
I don't know if this would improve anything.

This piece of code resides in the `form-close.ftl` template, meaning it's only rendered once for every form rendered with the bootstrap theme.
Only the items which have a tooltip will have an `i` tag with a class `s2b_tooltip`. So if there are no tooltips anywhere, there will be 0 items affected since nothing will match the selector `i.s2b_tooltip`.

I don't think the benefit of not executing a jQuery selector client-side would justify the complexity needed to have every single form element, that possibly has a tooltip, communicate that upwards.
